/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bean.ClienteBean;
import Model.Bean.ProdutoBean;
import Model.Bean.UtilBean;
import Model.Dao.ClienteDao;
import Model.Bean.FornecedoresBean;
import Model.Dao.FornecedoresDao;
import Model.Dao.ProdutoDao;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class CadastroProdutosView extends javax.swing.JFrame {

    
    public void Listar(){
        ProdutoDao dao = new ProdutoDao();
        List<ProdutoBean> lista = dao.ListarProdutos();
        DefaultTableModel produtos = (DefaultTableModel) ListaDeProdutosjTable1.getModel();
        produtos.setNumRows(0);
        for(ProdutoBean p:lista){
            produtos.addRow(new Object[]{
            
                p.getId(),
               p.getDescricao(),
               p.getPreco(),
               p.getQtd(),
               p.getFornecedor().getNome()
        });
        }
    }
    
    
    /**
     * Creates new form CadastroClientesView
     */
    public CadastroProdutosView() {
        initComponents();
        TxtCODIGO.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/ImagensView/FundoLogin.jpg"));
        Image image = icon.getImage();
        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        PainelDeGuiasjTabbedPane1 = new javax.swing.JTabbedPane();
        GUIA_DADOS_PRODUTO = new javax.swing.JPanel();
        TxtCODIGO = new javax.swing.JTextField();
        TxtDESCRICAO = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtPRECO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtQTD = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1FORNECEDOR = new javax.swing.JComboBox();
        SalvarjButton2 = new javax.swing.JButton();
        NovojButton1 = new javax.swing.JButton();
        EditarjButton3 = new javax.swing.JButton();
        excluirjButton4 = new javax.swing.JButton();
        CONSULTACLIENTES = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TxtPesquisaDescricao = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaDeProdutosjTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("CADASTRO DE PRODUTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        PainelDeGuiasjTabbedPane1.setBackground(new java.awt.Color(204, 255, 255));

        GUIA_DADOS_PRODUTO.setBackground(new java.awt.Color(204, 255, 255));

        TxtCODIGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCODIGOActionPerformed(evt);
            }
        });

        jLabel2.setText("CODIGO");

        jLabel3.setText("DESCRICAO");

        jLabel4.setText("PRECO");

        jLabel6.setText("QTD");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/7479647_search_magnifier_zoom_magnifying_find_icon(1).png"))); // NOI18N
        jButton7.setText("PESQUISAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel17.setText("FORNECEDORES");

        jComboBox1FORNECEDOR.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jComboBox1FORNECEDORAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jComboBox1FORNECEDOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1FORNECEDORMouseClicked(evt);
            }
        });

        SalvarjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/728995_clipboard_analysis_chart_checklist_data_icon.png"))); // NOI18N
        SalvarjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarjButton2ActionPerformed(evt);
            }
        });

        NovojButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/1493292_new_document_page_sheet_icon.png"))); // NOI18N
        NovojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovojButton1ActionPerformed(evt);
            }
        });

        EditarjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/46798_edit_control_icon.png"))); // NOI18N
        EditarjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarjButton3ActionPerformed(evt);
            }
        });

        excluirjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/1493279_delete_cancel_remove_icon.png"))); // NOI18N
        excluirjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GUIA_DADOS_PRODUTOLayout = new javax.swing.GroupLayout(GUIA_DADOS_PRODUTO);
        GUIA_DADOS_PRODUTO.setLayout(GUIA_DADOS_PRODUTOLayout);
        GUIA_DADOS_PRODUTOLayout.setHorizontalGroup(
            GUIA_DADOS_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIA_DADOS_PRODUTOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GUIA_DADOS_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(GUIA_DADOS_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(GUIA_DADOS_PRODUTOLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TxtCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(GUIA_DADOS_PRODUTOLayout.createSequentialGroup()
                            .addGroup(GUIA_DADOS_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(GUIA_DADOS_PRODUTOLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TxtDESCRICAO, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4)
                                .addGroup(GUIA_DADOS_PRODUTOLayout.createSequentialGroup()
                                    .addGap(69, 69, 69)
                                    .addComponent(TxtPRECO, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TxtQTD, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(16, 16, 16)
                            .addGroup(GUIA_DADOS_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(GUIA_DADOS_PRODUTOLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox1FORNECEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButton7))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GUIA_DADOS_PRODUTOLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(NovojButton1)
                        .addGap(91, 91, 91)
                        .addComponent(SalvarjButton2)
                        .addGap(87, 87, 87)
                        .addComponent(EditarjButton3)))
                .addGap(71, 71, 71)
                .addComponent(excluirjButton4)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        GUIA_DADOS_PRODUTOLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EditarjButton3, NovojButton1, SalvarjButton2, excluirjButton4});

        GUIA_DADOS_PRODUTOLayout.setVerticalGroup(
            GUIA_DADOS_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIA_DADOS_PRODUTOLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(GUIA_DADOS_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(GUIA_DADOS_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtDESCRICAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(GUIA_DADOS_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUIA_DADOS_PRODUTOLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(GUIA_DADOS_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtPRECO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(TxtQTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1FORNECEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(GUIA_DADOS_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NovojButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditarjButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SalvarjButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(GUIA_DADOS_PRODUTOLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluirjButton4)))
                .addGap(23, 23, 23))
        );

        GUIA_DADOS_PRODUTOLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EditarjButton3, NovojButton1, SalvarjButton2, excluirjButton4});

        PainelDeGuiasjTabbedPane1.addTab("CONSULTA DADOS DE PROTUDOS", GUIA_DADOS_PRODUTO);

        CONSULTACLIENTES.setBackground(new java.awt.Color(204, 255, 255));

        jLabel10.setText("NOME COMPLETO");

        TxtPesquisaDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPesquisaDescricaoKeyReleased(evt);
            }
        });

        ListaDeProdutosjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRICAO", "PRECO", "QTD", "FORNECEDORES"
            }
        ));
        ListaDeProdutosjTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaDeProdutosjTable1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ListaDeProdutosjTable1MouseReleased(evt);
            }
        });
        ListaDeProdutosjTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ListaDeProdutosjTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(ListaDeProdutosjTable1);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/7479647_search_magnifier_zoom_magnifying_find_icon(1).png"))); // NOI18N
        jButton6.setText("PESQUISAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CONSULTACLIENTESLayout = new javax.swing.GroupLayout(CONSULTACLIENTES);
        CONSULTACLIENTES.setLayout(CONSULTACLIENTESLayout);
        CONSULTACLIENTESLayout.setHorizontalGroup(
            CONSULTACLIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONSULTACLIENTESLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtPesquisaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        CONSULTACLIENTESLayout.setVerticalGroup(
            CONSULTACLIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONSULTACLIENTESLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CONSULTACLIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPesquisaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelDeGuiasjTabbedPane1.addTab("CONSULTA PRODUTOS", CONSULTACLIENTES);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PainelDeGuiasjTabbedPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelDeGuiasjTabbedPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCODIGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCODIGOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCODIGOActionPerformed

    private void SalvarjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarjButton2ActionPerformed
        // TODO add your handling code here:
        
       ProdutoBean produto = new ProdutoBean();
        produto.setDescricao(TxtDESCRICAO.getText());
        produto.setPreco(Double.parseDouble(TxtPRECO.getText()));
        produto.setQtd(Integer.parseInt(TxtQTD.getText()));
        produto.setFornecedor((FornecedoresBean) jComboBox1FORNECEDOR.getSelectedItem());
        
        ProdutoDao dao = new ProdutoDao();
        dao.cadastrarProduto(produto);
        new UtilBean().LimpaCampos(GUIA_DADOS_PRODUTO);
    }//GEN-LAST:event_SalvarjButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        Listar();
        
    }//GEN-LAST:event_formWindowActivated

    private void EditarjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarjButton3ActionPerformed
        // TODO add your handling code here:
        
        ProdutoBean produto = new ProdutoBean();
        produto.setDescricao(TxtDESCRICAO.getText());
        produto.setPreco(Double.parseDouble(TxtPRECO.getText()));
       produto.setQtd(Integer.parseInt(TxtQTD.getText()));
       FornecedoresBean f = new FornecedoresBean();
        f =(FornecedoresBean)jComboBox1FORNECEDOR.getSelectedItem();
        produto.setFornecedor(f);
        produto.setId(Integer.parseInt(TxtCODIGO.getText()));
        ProdutoDao dao = new ProdutoDao();
        dao.alterarProduto(produto);
        
    }//GEN-LAST:event_EditarjButton3ActionPerformed

    private void excluirjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButton4ActionPerformed
        // TODO add your handling code here:
        ProdutoDao dao = new ProdutoDao();
        ProdutoBean produto= new ProdutoBean();
            
        produto.setId(Integer.parseInt(TxtCODIGO.getText()));
        dao.excluirProduto(produto);
          new UtilBean().LimpaCampos(GUIA_DADOS_PRODUTO);
    }//GEN-LAST:event_excluirjButton4ActionPerformed

    private void ListaDeProdutosjTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDeProdutosjTable1MouseReleased
        // TODO add your handling code here:        
        
        
    }//GEN-LAST:event_ListaDeProdutosjTable1MouseReleased

    private void ListaDeProdutosjTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDeProdutosjTable1MouseClicked
        // TODO add your handling code here:
        
                PainelDeGuiasjTabbedPane1.setSelectedIndex(0);
        TxtCODIGO.setText(ListaDeProdutosjTable1.getValueAt(ListaDeProdutosjTable1.getSelectedRow(), 0).toString());
            TxtDESCRICAO.setText(ListaDeProdutosjTable1.getValueAt(ListaDeProdutosjTable1.getSelectedRow(), 1).toString());
            TxtPRECO.setText(ListaDeProdutosjTable1.getValueAt(ListaDeProdutosjTable1.getSelectedRow(), 2).toString());
            TxtQTD.setText(ListaDeProdutosjTable1.getValueAt(ListaDeProdutosjTable1.getSelectedRow(), 3).toString());
            jComboBox1FORNECEDOR.setSelectedItem(ListaDeProdutosjTable1.getValueAt(ListaDeProdutosjTable1.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_ListaDeProdutosjTable1MouseClicked

    private void ListaDeProdutosjTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ListaDeProdutosjTable1KeyReleased
        // TODO add your handling code here:
        
        
                                      
        
    }//GEN-LAST:event_ListaDeProdutosjTable1KeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        String nome = TxtDESCRICAO.getText();
        ProdutoBean produto = new ProdutoBean();
        ProdutoDao dao = new ProdutoDao();
        produto=dao.pesquisaNomeP(nome);
         jComboBox1FORNECEDOR.removeAllItems();
        
        if (produto.getDescricao()!= null) {
            TxtCODIGO.setText(String.valueOf(produto.getId()));
             TxtDESCRICAO.setText(produto.getDescricao());
            TxtPRECO.setText(String.valueOf(produto.getPreco()));
            TxtQTD.setText(String.valueOf(produto.getQtd()));
            FornecedoresBean f = new FornecedoresBean();
            FornecedoresDao fdao = new FornecedoresDao();
            f = fdao.pesquisaFornecedores(produto.getFornecedor().getNome());
             jComboBox1FORNECEDOR.getModel().setSelectedItem(f);
                     

        }else{
            
            JOptionPane.showMessageDialog(null, "Produto não encontrado");
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void NovojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovojButton1ActionPerformed
        // TODO add your handling code here:
        
        UtilBean util = new UtilBean();
        util.LimpaCampos(GUIA_DADOS_PRODUTO);
        
        
    }//GEN-LAST:event_NovojButton1ActionPerformed

    private void TxtPesquisaDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisaDescricaoKeyReleased
        // TODO add your handling code here:
       
        String nome = "%"+TxtPesquisaDescricao.getText()+ "%";
           ProdutoDao dao = new ProdutoDao();
           List<ProdutoBean> lista = dao.pesquisaNomeProduto(nome);
          DefaultTableModel dados =(DefaultTableModel)ListaDeProdutosjTable1.getModel();
       dados.setNumRows(0);
          for(ProdutoBean p: lista){
              dados.addRow(new Object[]{
              p.getId(),
                  p.getDescricao(),
                  p.getPreco(),
                  p.getQtd(),
                  p.getFornecedor().getNome()
          });
          }
    }//GEN-LAST:event_TxtPesquisaDescricaoKeyReleased

    private void jComboBox1FORNECEDORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1FORNECEDORMouseClicked
        // TODO add your handling code here:
        FornecedoresDao dao = new FornecedoresDao();
        List<FornecedoresBean> listaFornecedores = dao.ListarOsFornecedores();
     jComboBox1FORNECEDOR.removeAllItems();
        for(FornecedoresBean f: listaFornecedores){
            jComboBox1FORNECEDOR.addItem(f);
        }
        
    }//GEN-LAST:event_jComboBox1FORNECEDORMouseClicked

    private void jComboBox1FORNECEDORAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox1FORNECEDORAncestorAdded
        // TODO add your handling code here:
        FornecedoresDao dao = new FornecedoresDao();
        List<FornecedoresBean> listaFornecedores = dao.ListarOsFornecedores();
jComboBox1FORNECEDOR.removeAllItems();
        for(FornecedoresBean f: listaFornecedores){
            jComboBox1FORNECEDOR.addItem(f);
        }
        
    }//GEN-LAST:event_jComboBox1FORNECEDORAncestorAdded

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        String nome = "%"+TxtPesquisaDescricao.getText()+ "%";
           ProdutoDao dao = new ProdutoDao();
           List<ProdutoBean> lista = dao.pesquisaNomeProduto(nome);
          DefaultTableModel dados =(DefaultTableModel)ListaDeProdutosjTable1.getModel();
       dados.setNumRows(0);
          for(ProdutoBean p: lista){
              dados.addRow(new Object[]{
              p.getId(),
                  p.getDescricao(),
                  p.getPreco(),
                  p.getQtd(),
                  p.getFornecedor().getNome()
          });
          }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CONSULTACLIENTES;
    private javax.swing.JButton EditarjButton3;
    private javax.swing.JPanel GUIA_DADOS_PRODUTO;
    private javax.swing.JTable ListaDeProdutosjTable1;
    private javax.swing.JButton NovojButton1;
    private javax.swing.JTabbedPane PainelDeGuiasjTabbedPane1;
    private javax.swing.JButton SalvarjButton2;
    private javax.swing.JTextField TxtCODIGO;
    private javax.swing.JTextField TxtDESCRICAO;
    private javax.swing.JTextField TxtPRECO;
    private javax.swing.JTextField TxtPesquisaDescricao;
    private javax.swing.JTextField TxtQTD;
    private javax.swing.JButton excluirjButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1FORNECEDOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
