/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bean.ClienteBean;
import Model.Bean.UtilBean;
import Model.Dao.ClienteDao;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class CadastroClientesView extends javax.swing.JFrame {

    
    public void ListarClientes(){
        ClienteDao dao = new ClienteDao();
        List<ClienteBean> lista = dao.ListarOsClientes();
        DefaultTableModel clientes = (DefaultTableModel) ListaDeClientesjTable1.getModel();
        clientes.setNumRows(0);
        for(ClienteBean c:lista){
            clientes.addRow(new Object[]{
            
                c.getId(),
               c.getNome(),
               c.getRg(),
               c.getCpf(),
               c.getEmail(),
               c.getTelefone(),
               c.getCelular(),
              c.getCep(),
               c.getEndereco(),
               c.getNumero(),
              c.getComplemento(),
                c.getBairro(),
               c.getCidade(),
               c.getEstado()
        });
        }
    }
    
    
    /**
     * Creates new form CadastroClientesView
     */
    public CadastroClientesView() {
        initComponents();
        TxtCODIGO.setEnabled(false);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/ImagensView/FundoLogin.jpg"));
        Image image = icon.getImage();
        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        PainelDeGuiasjTabbedPane1 = new javax.swing.JTabbedPane();
        GUIA_DADOS_PESSOAIS = new javax.swing.JPanel();
        TxtCODIGO = new javax.swing.JTextField();
        TxtNOME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtEMAIL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtCEP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtENDERECO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtNUMERO = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ufjComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtCOMPLEMENTO = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        TxtBAIRRO = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxtCIDADE = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxtRG = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtCPF = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        TxtCELULAR = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtTELEFONE = new javax.swing.JTextField();
        CONSULTACLIENTES = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TxtPesquisaNome = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaDeClientesjTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        NovojButton3 = new javax.swing.JButton();
        SalvarjButton4 = new javax.swing.JButton();
        EditarjButton5 = new javax.swing.JButton();
        excluirjButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("CADASTRO E CONTROLE DE CLIENTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        PainelDeGuiasjTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        GUIA_DADOS_PESSOAIS.setBackground(new java.awt.Color(255, 255, 255));

        TxtCODIGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCODIGOActionPerformed(evt);
            }
        });

        jLabel2.setText("CODIGO");

        jLabel3.setText("NOME COMPLETO");

        jLabel4.setText("EMAIL");

        jLabel5.setText("CEP");

        TxtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCEPActionPerformed(evt);
            }
        });

        jLabel6.setText("ENDERECO");

        jLabel7.setText("Nº");

        jLabel8.setText("UF");

        ufjComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP", "RJ", "MG", "PR", "PE", "CE", "AC", " ", " " }));

        jLabel9.setText("COMPLEMENTO");

        TxtCOMPLEMENTO.setColumns(20);
        TxtCOMPLEMENTO.setRows(5);
        jScrollPane1.setViewportView(TxtCOMPLEMENTO);

        jLabel11.setText("BAIRRO");

        jLabel12.setText("CIDADE");

        jLabel13.setText("RG");

        jLabel14.setText("CPF");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/7479647_search_magnifier_zoom_magnifying_find_icon(1).png"))); // NOI18N
        jButton7.setText("PESQUISAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel15.setText("CELULAR");

        jLabel16.setText("TELEFONE");

        javax.swing.GroupLayout GUIA_DADOS_PESSOAISLayout = new javax.swing.GroupLayout(GUIA_DADOS_PESSOAIS);
        GUIA_DADOS_PESSOAIS.setLayout(GUIA_DADOS_PESSOAISLayout);
        GUIA_DADOS_PESSOAISLayout.setHorizontalGroup(
            GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtENDERECO, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel11))
                            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(8, 8, 8)
                                .addComponent(TxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(ufjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                        .addComponent(jLabel9))))
                            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtBAIRRO, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                .addComponent(TxtCELULAR, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel16)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                        .addComponent(TxtNUMERO, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                        .addComponent(TxtTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))))
            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GUIA_DADOS_PESSOAISLayout.setVerticalGroup(
            GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(TxtENDERECO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(TxtBAIRRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(TxtNUMERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TxtCELULAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(TxtTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(TxtCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ufjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(39, 39, 39)
                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(TxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        PainelDeGuiasjTabbedPane1.addTab("CADASTRAR DADOS DE CLIENTE", GUIA_DADOS_PESSOAIS);

        CONSULTACLIENTES.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("NOME COMPLETO");

        TxtPesquisaNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPesquisaNomeKeyReleased(evt);
            }
        });

        ListaDeClientesjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOME", "RG", "CPF", "EMAIL", "TELEFONE", "CELULAR", "CEP", "ENDERECO", "NUMERO", "COMPL.", "BAIRRO", "CIDADE", "UF"
            }
        ));
        ListaDeClientesjTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaDeClientesjTable1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ListaDeClientesjTable1MouseReleased(evt);
            }
        });
        ListaDeClientesjTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ListaDeClientesjTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(ListaDeClientesjTable1);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/7479647_search_magnifier_zoom_magnifying_find_icon(1).png"))); // NOI18N
        jButton6.setText("PESQUISAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CONSULTACLIENTESLayout = new javax.swing.GroupLayout(CONSULTACLIENTES);
        CONSULTACLIENTES.setLayout(CONSULTACLIENTESLayout);
        CONSULTACLIENTESLayout.setHorizontalGroup(
            CONSULTACLIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONSULTACLIENTESLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
        );
        CONSULTACLIENTESLayout.setVerticalGroup(
            CONSULTACLIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONSULTACLIENTESLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CONSULTACLIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelDeGuiasjTabbedPane1.addTab("CONSULTA CLIENTE", CONSULTACLIENTES);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        NovojButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/1493292_new_document_page_sheet_icon.png"))); // NOI18N
        NovojButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovojButton1ActionPerformed(evt);
            }
        });

        SalvarjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/46775_add_user_icon.png"))); // NOI18N
        SalvarjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarjButton2ActionPerformed(evt);
            }
        });

        EditarjButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/48757_document_edit_icon.png"))); // NOI18N
        EditarjButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarjButton3ActionPerformed(evt);
            }
        });

        excluirjButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/1493279_delete_cancel_remove_icon.png"))); // NOI18N
        excluirjButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(NovojButton3)
                .addGap(120, 120, 120)
                .addComponent(SalvarjButton4)
                .addGap(108, 108, 108)
                .addComponent(EditarjButton5)
                .addGap(98, 98, 98)
                .addComponent(excluirjButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EditarjButton5, NovojButton3, SalvarjButton4, excluirjButton6});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(excluirjButton6)
                    .addComponent(EditarjButton5)
                    .addComponent(SalvarjButton4)
                    .addComponent(NovojButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EditarjButton5, SalvarjButton4, excluirjButton6});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PainelDeGuiasjTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelDeGuiasjTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCODIGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCODIGOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCODIGOActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        ListarClientes();
        
    }//GEN-LAST:event_formWindowActivated

    private void ListaDeClientesjTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDeClientesjTable1MouseReleased
        // TODO add your handling code here:        
        
        
    }//GEN-LAST:event_ListaDeClientesjTable1MouseReleased

    private void ListaDeClientesjTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDeClientesjTable1MouseClicked
        // TODO add your handling code here:
        
                PainelDeGuiasjTabbedPane1.setSelectedIndex(0);
        TxtCODIGO.setText(ListaDeClientesjTable1.getValueAt(ListaDeClientesjTable1.getSelectedRow(), 0).toString());
            TxtNOME.setText(ListaDeClientesjTable1.getValueAt(ListaDeClientesjTable1.getSelectedRow(), 1).toString());
            TxtRG.setText(ListaDeClientesjTable1.getValueAt(ListaDeClientesjTable1.getSelectedRow(), 2).toString());
            TxtCPF.setText(ListaDeClientesjTable1.getValueAt(ListaDeClientesjTable1.getSelectedRow(), 3).toString());
            TxtEMAIL.setText(ListaDeClientesjTable1.getValueAt(ListaDeClientesjTable1.getSelectedRow(), 4).toString());
            TxtTELEFONE.setText(ListaDeClientesjTable1.getValueAt(ListaDeClientesjTable1.getSelectedRow(), 5).toString());
            TxtCELULAR.setText(ListaDeClientesjTable1.getValueAt(ListaDeClientesjTable1.getSelectedRow(), 6).toString());
            TxtCEP.setText(ListaDeClientesjTable1.getValueAt(ListaDeClientesjTable1.getSelectedRow(), 7).toString());
            TxtENDERECO.setText(ListaDeClientesjTable1.getValueAt(ListaDeClientesjTable1.getSelectedRow(), 8).toString());
            TxtNUMERO.setText(ListaDeClientesjTable1.getValueAt(ListaDeClientesjTable1.getSelectedRow(), 9).toString());
            TxtCOMPLEMENTO.setText(ListaDeClientesjTable1.getValueAt(ListaDeClientesjTable1.getSelectedRow(), 10).toString());
            TxtBAIRRO.setText(ListaDeClientesjTable1.getValueAt(ListaDeClientesjTable1.getSelectedRow(), 11).toString());
            TxtCIDADE.setText(ListaDeClientesjTable1.getValueAt(ListaDeClientesjTable1.getSelectedRow(), 12).toString());
          ufjComboBox1.setSelectedItem(ListaDeClientesjTable1.getValueAt(ListaDeClientesjTable1.getSelectedRow(), 13).toString());
        
    }//GEN-LAST:event_ListaDeClientesjTable1MouseClicked

    private void ListaDeClientesjTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ListaDeClientesjTable1KeyReleased
        // TODO add your handling code here:
        
        
                                      
        
    }//GEN-LAST:event_ListaDeClientesjTable1KeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        String nome = TxtNOME.getText();
        ClienteBean cliente = new ClienteBean();
        ClienteDao dao = new ClienteDao();
        cliente=dao.pesquisaCliente(nome);
        
        
        if (cliente.getNome() != null) {
            TxtCODIGO.setText(String.valueOf(cliente.getId()));
             TxtNOME.setText(cliente.getNome());
              TxtRG.setText(cliente.getRg());
               TxtCPF.setText(cliente.getCpf());
                TxtEMAIL.setText(cliente.getEmail());
                TxtTELEFONE.setText(cliente.getTelefone());
                 TxtCELULAR.setText(cliente.getCelular());
                  TxtCEP.setText(cliente.getCep());
                   TxtENDERECO.setText(cliente.getEndereco());
                 TxtNUMERO.setText(cliente.getNumero());
                  TxtCOMPLEMENTO.setText(cliente.getComplemento());
                   TxtBAIRRO.setText(cliente.getBairro());
                    TxtCIDADE.setText(cliente.getCidade());
                     ufjComboBox1.setSelectedItem(cliente.getEstado());
                
            
        }else{
            JOptionPane.showMessageDialog(null, "Cliente não encontrado");
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void TxtPesquisaNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisaNomeKeyReleased
        // TODO add your handling code here:
       
        String nome = "%" +TxtPesquisaNome.getText() +"%";
        ClienteDao dao = new ClienteDao();
        List<ClienteBean> lista = dao.pesquisarNome(nome);
        DefaultTableModel dados =(DefaultTableModel)ListaDeClientesjTable1.getModel();
        dados.setNumRows(0);
        
        for(ClienteBean c : lista){
            dados.addRow(new Object[]{
                c.getId(),
               c.getNome(),
               c.getRg(),
               c.getCpf(),
               c.getEmail(),
               c.getTelefone(),
               c.getCelular(),
                c.getCep(),
               c.getEndereco(),
               c.getNumero(),
              c.getComplemento(),
                c.getBairro(),
               c.getCidade(),
               c.getEstado()
            });
                  
        }
       
    }//GEN-LAST:event_TxtPesquisaNomeKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        String nome = "%" +TxtPesquisaNome.getText() +"%";
        ClienteDao dao = new ClienteDao();
        List<ClienteBean> lista = dao.pesquisarNome(nome);
        DefaultTableModel dados =(DefaultTableModel)ListaDeClientesjTable1.getModel();
        dados.setNumRows(0);
        
        for(ClienteBean c : lista){
            dados.addRow(new Object[]{
                c.getId(),
               c.getNome(),
               c.getRg(),
               c.getCpf(),
               c.getEmail(),
               c.getTelefone(),
               c.getCelular(),
              c.getCep(),
               c.getEndereco(),
               c.getNumero(),
              c.getComplemento(),
                c.getBairro(),
               c.getCidade(),
               c.getEstado()
            });
                  
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void TxtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCEPActionPerformed

    private void excluirjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButton4ActionPerformed
        // TODO add your handling code here:
        ClienteDao dao = new ClienteDao();
        ClienteBean cliente= new ClienteBean();

        cliente.setId(Integer.parseInt(TxtCODIGO.getText()));
        dao.excluirCliente(cliente);
        new UtilBean().LimpaCampos(GUIA_DADOS_PESSOAIS);
    }//GEN-LAST:event_excluirjButton4ActionPerformed

    private void EditarjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarjButton3ActionPerformed
        // TODO add your handling code here:

        ClienteBean cliente = new ClienteBean();
        cliente.setNome(TxtNOME.getText());
        cliente.setRg(TxtRG.getText());
        cliente.setCpf(TxtCPF.getText());
        cliente.setEmail(TxtEMAIL.getText());
        cliente.setTelefone(TxtTELEFONE.getText());
        cliente.setCelular(TxtCELULAR.getText());
        cliente.setCep(TxtCEP.getText());
        cliente.setEndereco(TxtENDERECO.getText());
        cliente.setNumero(TxtNUMERO.getText());
        cliente.setComplemento(TxtCOMPLEMENTO.getText());
        cliente.setBairro(TxtBAIRRO.getText());
        cliente.setCidade(TxtCIDADE.getText());
        cliente.setEstado(ufjComboBox1.getSelectedItem().toString());
        cliente.setId(Integer.parseInt(TxtCODIGO.getText()));

        ClienteDao dao = new ClienteDao();
        dao.alterarCliente(cliente);

    }//GEN-LAST:event_EditarjButton3ActionPerformed

    private void SalvarjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarjButton2ActionPerformed
        // TODO add your handling code here:

        ClienteBean cliente = new ClienteBean();
        cliente.setNome(TxtNOME.getText());
        cliente.setRg(TxtRG.getText());
        cliente.setCpf(TxtCPF.getText());
        cliente.setEmail(TxtEMAIL.getText());
        cliente.setTelefone(TxtTELEFONE.getText());
        cliente.setCelular(TxtCELULAR.getText());
        cliente.setCep(TxtCEP.getText());
        cliente.setEndereco(TxtENDERECO.getText());
        cliente.setNumero(TxtNUMERO.getText());
        cliente.setComplemento(TxtCOMPLEMENTO.getText());
        cliente.setBairro(TxtBAIRRO.getText());
        cliente.setCidade(TxtCIDADE.getText());
        cliente.setEstado(ufjComboBox1.getSelectedItem().toString());

        ClienteDao dao = new ClienteDao();
        dao.cadastrarClientes(cliente);
        new UtilBean().LimpaCampos(GUIA_DADOS_PESSOAIS);
    }//GEN-LAST:event_SalvarjButton2ActionPerformed

    private void NovojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovojButton1ActionPerformed
        // TODO add your handling code here:

        UtilBean util = new UtilBean();
        util.LimpaCampos(GUIA_DADOS_PESSOAIS);
        TxtCOMPLEMENTO.setText("");

    }//GEN-LAST:event_NovojButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClientesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CONSULTACLIENTES;
    private javax.swing.JButton EditarjButton5;
    private javax.swing.JPanel GUIA_DADOS_PESSOAIS;
    private javax.swing.JTable ListaDeClientesjTable1;
    private javax.swing.JButton NovojButton3;
    private javax.swing.JTabbedPane PainelDeGuiasjTabbedPane1;
    private javax.swing.JButton SalvarjButton4;
    private javax.swing.JTextField TxtBAIRRO;
    private javax.swing.JTextField TxtCELULAR;
    private javax.swing.JTextField TxtCEP;
    private javax.swing.JTextField TxtCIDADE;
    private javax.swing.JTextField TxtCODIGO;
    private javax.swing.JTextArea TxtCOMPLEMENTO;
    private javax.swing.JTextField TxtCPF;
    private javax.swing.JTextField TxtEMAIL;
    private javax.swing.JTextField TxtENDERECO;
    private javax.swing.JTextField TxtNOME;
    private javax.swing.JTextField TxtNUMERO;
    private javax.swing.JTextField TxtPesquisaNome;
    private javax.swing.JTextField TxtRG;
    private javax.swing.JTextField TxtTELEFONE;
    private javax.swing.JButton excluirjButton6;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> ufjComboBox1;
    // End of variables declaration//GEN-END:variables
}
