/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bean.ClienteBean;
import Model.Bean.FuncionarioBean;
import Model.Bean.UtilBean;
import Model.Dao.ClienteDao;
import Model.Dao.FuncionarioDao;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CadastroFuncionarioView extends javax.swing.JFrame {

    
    public void ListarFuncionarios(){
        FuncionarioDao dao = new FuncionarioDao();
        List<FuncionarioBean> lista = dao.ListarOsFuncionarios();
        DefaultTableModel funcionarios = (DefaultTableModel) ListaDeFuncionariosjTable1.getModel();
        funcionarios.setNumRows(0);
        for(FuncionarioBean c:lista){
            funcionarios.addRow(new Object[]{
            
                c.getId(),
               c.getNome(),
               c.getRg(),
               c.getCpf(),
               c.getEmail(),
               c.getSenha(),
               c.getCargo(),
               c.getNivel_acesso(),
               c.getTelefone(),
               c.getCelular(),
              c.getCep(),
               c.getEndereco(),
               c.getNumero(),
              c.getComplemento(),
                c.getBairro(),
               c.getCidade(),
               c.getEstado()
        });
        }
    }
    
    
    /**
     * Creates new form CadastroClientesView
     */
    public CadastroFuncionarioView() {
        initComponents();
        TxtCODIGO.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/ImagensView/FundoLogin.jpg"));
        Image image = icon.getImage();
        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        PainelDeGuiasjTabbedPane1 = new javax.swing.JTabbedPane();
        GUIA_DADOS_PESSOAIS = new javax.swing.JPanel();
        TxtCODIGO = new javax.swing.JTextField();
        TxtNOME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtEMAIL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtCEP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtENDERECO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtNUMERO = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ufjComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtCOMPLEMENTO = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        TxtBAIRRO = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxtCIDADE = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxtRG = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtCPF = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        TxtCELULAR = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtTELEFONE = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TxtCARGO = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TxtSENHA = new javax.swing.JPasswordField();
        NivelAcessojComboBox1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        CONSULTACLIENTES = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TxtPesquisaNome = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaDeFuncionariosjTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        NovojButton1 = new javax.swing.JButton();
        SalvarjButton2 = new javax.swing.JButton();
        EditarjButton3 = new javax.swing.JButton();
        excluirjButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("CADASTRO E CONTROLE DE FUNCIONARIOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        GUIA_DADOS_PESSOAIS.setBackground(new java.awt.Color(255, 255, 255));

        TxtCODIGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCODIGOActionPerformed(evt);
            }
        });

        jLabel2.setText("CODIGO");

        jLabel3.setText("NOME COMPLETO");

        jLabel4.setText("EMAIL");

        jLabel5.setText("CEP");

        jLabel6.setText("ENDERECO");

        jLabel7.setText("Nº");

        jLabel8.setText("UF");

        ufjComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP", "RJ", "MG", "PR", "PE", "CE", "AC", " ", " " }));

        jLabel9.setText("COMPL");

        TxtCOMPLEMENTO.setColumns(20);
        TxtCOMPLEMENTO.setRows(5);
        jScrollPane1.setViewportView(TxtCOMPLEMENTO);

        jLabel11.setText("BAIRRO");

        jLabel12.setText("CIDADE");

        jLabel13.setText("RG");

        jLabel14.setText("CPF");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/7479647_search_magnifier_zoom_magnifying_find_icon(1).png"))); // NOI18N
        jButton7.setText("PESQUISAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel15.setText("CELULAR");

        jLabel16.setText("TELEFONE");

        jLabel17.setText("CARGO");

        jLabel19.setText("SENHA");

        NivelAcessojComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USUARIO", "ADMIN" }));

        jLabel18.setText("Acesso");

        javax.swing.GroupLayout GUIA_DADOS_PESSOAISLayout = new javax.swing.GroupLayout(GUIA_DADOS_PESSOAIS);
        GUIA_DADOS_PESSOAIS.setLayout(GUIA_DADOS_PESSOAISLayout);
        GUIA_DADOS_PESSOAISLayout.setHorizontalGroup(
            GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                .addComponent(TxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12))
                            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                .addComponent(TxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtBAIRRO, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtNUMERO, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(TxtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                        .addComponent(jButton7)
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtCELULAR, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(ufjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(TxtENDERECO, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(NivelAcessojComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(109, 109, 109)))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtCARGO, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtSENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(45, Short.MAX_VALUE))))
        );
        GUIA_DADOS_PESSOAISLayout.setVerticalGroup(
            GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(TxtCELULAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(TxtTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TxtENDERECO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TxtNUMERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBAIRRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(34, 34, 34)
                .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GUIA_DADOS_PESSOAISLayout.createSequentialGroup()
                                .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(TxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(TxtCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(ufjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(TxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(GUIA_DADOS_PESSOAISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(TxtCARGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(TxtSENHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NivelAcessojComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        PainelDeGuiasjTabbedPane1.addTab("CADASTRAR DADOS DE FUNCIONARIOS", GUIA_DADOS_PESSOAIS);

        CONSULTACLIENTES.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("NOME COMPLETO");

        TxtPesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPesquisaNomeActionPerformed(evt);
            }
        });
        TxtPesquisaNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPesquisaNomeKeyReleased(evt);
            }
        });

        ListaDeFuncionariosjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOME", "RG", "CPF", "EMAIL", "SENHA", "CARGO", "ACESSO", "TELEFONE", "CELULAR", "CEP", "ENDERECO", "NUMERO", "COMPL.", "BAIRRO", "CIDADE", "UF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListaDeFuncionariosjTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaDeFuncionariosjTable1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ListaDeFuncionariosjTable1MouseReleased(evt);
            }
        });
        ListaDeFuncionariosjTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ListaDeFuncionariosjTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(ListaDeFuncionariosjTable1);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/7479647_search_magnifier_zoom_magnifying_find_icon(1).png"))); // NOI18N
        jButton6.setText("PESQUISAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CONSULTACLIENTESLayout = new javax.swing.GroupLayout(CONSULTACLIENTES);
        CONSULTACLIENTES.setLayout(CONSULTACLIENTESLayout);
        CONSULTACLIENTESLayout.setHorizontalGroup(
            CONSULTACLIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONSULTACLIENTESLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
        );
        CONSULTACLIENTESLayout.setVerticalGroup(
            CONSULTACLIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONSULTACLIENTESLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CONSULTACLIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelDeGuiasjTabbedPane1.addTab("CONSULTA FUNCIONARIOS", CONSULTACLIENTES);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        NovojButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/1493292_new_document_page_sheet_icon.png"))); // NOI18N
        NovojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovojButton1ActionPerformed(evt);
            }
        });

        SalvarjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/8396413_id_card_identity_name_identification_icon.png"))); // NOI18N
        SalvarjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarjButton2ActionPerformed(evt);
            }
        });

        EditarjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/48757_document_edit_icon.png"))); // NOI18N
        EditarjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarjButton3ActionPerformed(evt);
            }
        });

        excluirjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/1493279_delete_cancel_remove_icon.png"))); // NOI18N
        excluirjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(NovojButton1)
                .addGap(98, 98, 98)
                .addComponent(SalvarjButton2)
                .addGap(110, 110, 110)
                .addComponent(EditarjButton3)
                .addGap(97, 97, 97)
                .addComponent(excluirjButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EditarjButton3, NovojButton1, SalvarjButton2, excluirjButton4});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditarjButton3)
                    .addComponent(SalvarjButton2)
                    .addComponent(NovojButton1))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(excluirjButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {EditarjButton3, SalvarjButton2, excluirjButton4});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PainelDeGuiasjTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelDeGuiasjTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCODIGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCODIGOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCODIGOActionPerformed

    private void SalvarjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarjButton2ActionPerformed
        // TODO add your handling code here:
        
        FuncionarioBean funcionario = new FuncionarioBean();
        funcionario.setNome(TxtNOME.getText());
        funcionario.setRg(TxtRG.getText());
        funcionario.setCpf(TxtCPF.getText());
        funcionario.setEmail(TxtEMAIL.getText());
        funcionario.setSenha(TxtSENHA.getText());
        funcionario.setCargo(TxtCARGO.getText());
       funcionario.setNivel_acesso(NivelAcessojComboBox1.getSelectedItem().toString());
        funcionario.setTelefone(TxtTELEFONE.getText());
        funcionario.setCelular(TxtCELULAR.getText());
        funcionario.setCep(TxtCEP.getText());
        funcionario.setEndereco(TxtENDERECO.getText());
        funcionario.setNumero(TxtNUMERO.getText());
        funcionario.setComplemento(TxtCOMPLEMENTO.getText());
        funcionario.setBairro(TxtBAIRRO.getText());
        funcionario.setCidade(TxtCIDADE.getText());
        funcionario.setEstado(ufjComboBox1.getSelectedItem().toString());
        
        FuncionarioDao dao = new FuncionarioDao();
        dao.cadastrarFuncionarios(funcionario);
        new UtilBean().LimpaCampos(GUIA_DADOS_PESSOAIS);
    }//GEN-LAST:event_SalvarjButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        ListarFuncionarios();
        
    }//GEN-LAST:event_formWindowActivated

    private void EditarjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarjButton3ActionPerformed
        // TODO add your handling code here:
        FuncionarioBean funcionario = new FuncionarioBean();
        funcionario.setNome(TxtNOME.getText());
        funcionario.setRg(TxtRG.getText());
        funcionario.setCpf(TxtCPF.getText());
        funcionario.setEmail(TxtEMAIL.getText());
        funcionario.setTelefone(TxtTELEFONE.getText()); 
        funcionario.setSenha(TxtSENHA.getText());
        funcionario.setCargo(TxtCARGO.getText());
        funcionario.setNivel_acesso( NivelAcessojComboBox1.getSelectedItem().toString());
       funcionario.setCelular(TxtCELULAR.getText());
        funcionario.setCep(TxtCEP.getText());
        funcionario.setEndereco(TxtENDERECO.getText());
        funcionario.setNumero(TxtNUMERO.getText());
        funcionario.setComplemento(TxtCOMPLEMENTO.getText());
        funcionario.setBairro(TxtBAIRRO.getText());
        funcionario.setCidade(TxtCIDADE.getText());
        funcionario.setEstado(ufjComboBox1.getSelectedItem().toString());
        funcionario.setId(Integer.parseInt(TxtCODIGO.getText()));
        
        FuncionarioDao dao = new FuncionarioDao();
        dao.alterarFuncionario(funcionario);
       
    }//GEN-LAST:event_EditarjButton3ActionPerformed

    private void excluirjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButton4ActionPerformed
        // TODO add your handling code here:
        FuncionarioDao dao = new FuncionarioDao();
        FuncionarioBean funcionario= new FuncionarioBean();
            
        funcionario.setId(Integer.parseInt(TxtCODIGO.getText()));
        dao.excluirFuncionario(funcionario);
         new UtilBean().LimpaCampos(GUIA_DADOS_PESSOAIS);
    }//GEN-LAST:event_excluirjButton4ActionPerformed

    private void ListaDeFuncionariosjTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDeFuncionariosjTable1MouseReleased
        // TODO add your handling code here:        
        
        
    }//GEN-LAST:event_ListaDeFuncionariosjTable1MouseReleased

    private void ListaDeFuncionariosjTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDeFuncionariosjTable1MouseClicked
        // TODO add your handling code here:
        
                PainelDeGuiasjTabbedPane1.setSelectedIndex(0);
        TxtCODIGO.setText(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 0).toString());
            TxtNOME.setText(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 1).toString());
            TxtRG.setText(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 2).toString());
            TxtCPF.setText(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 3).toString());
            TxtEMAIL.setText(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 4).toString());
             TxtSENHA.setText(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 5).toString());
              TxtCARGO.setText(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 6).toString());
              NivelAcessojComboBox1.setSelectedItem(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 7).toString());
            TxtTELEFONE.setText(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 8).toString());
            TxtCELULAR.setText(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 9).toString());
            TxtCEP.setText(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 10).toString());
            TxtENDERECO.setText(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 11).toString());
            TxtNUMERO.setText(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 12).toString());
            TxtCOMPLEMENTO.setText(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 13).toString());
            TxtBAIRRO.setText(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 14).toString());
            TxtCIDADE.setText(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 15).toString());
          ufjComboBox1.setSelectedItem(ListaDeFuncionariosjTable1.getValueAt(ListaDeFuncionariosjTable1.getSelectedRow(), 16).toString());
        
    }//GEN-LAST:event_ListaDeFuncionariosjTable1MouseClicked

    private void ListaDeFuncionariosjTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ListaDeFuncionariosjTable1KeyReleased
        // TODO add your handling code here:
        
        
                                      
        
    }//GEN-LAST:event_ListaDeFuncionariosjTable1KeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        String nome = TxtNOME.getText();
        FuncionarioBean funcionario = new FuncionarioBean();
        FuncionarioDao dao = new FuncionarioDao();
        funcionario=dao.pesquisaFuncionario(nome);
        
        
        if (funcionario.getNome() != null) {
            TxtCODIGO.setText(String.valueOf(funcionario.getId()));
             TxtNOME.setText(funcionario.getNome());
              TxtRG.setText(funcionario.getRg());
               TxtCPF.setText(funcionario.getCpf());
                TxtEMAIL.setText(funcionario.getEmail());
                TxtSENHA.setText(funcionario.getSenha());
                TxtCARGO.setText(funcionario.getCargo());
                NivelAcessojComboBox1.setSelectedItem(funcionario.getNivel_acesso());
                TxtTELEFONE.setText(funcionario.getTelefone());
                 TxtCELULAR.setText(funcionario.getCelular());
                  TxtCEP.setText(funcionario.getCep());
                   TxtENDERECO.setText(funcionario.getEndereco());
                 TxtNUMERO.setText(funcionario.getNumero());
                  TxtCOMPLEMENTO.setText(funcionario.getComplemento());
                   TxtBAIRRO.setText(funcionario.getBairro());
                    TxtCIDADE.setText(funcionario.getCidade());
                     ufjComboBox1.setSelectedItem(funcionario.getEstado());
                
            
        }else{
            JOptionPane.showMessageDialog(null, "Funcionario não encontrado");
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void NovojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovojButton1ActionPerformed
        // TODO add your handling code here:
        
        UtilBean util = new UtilBean();
        util.LimpaCampos(GUIA_DADOS_PESSOAIS);
        TxtCOMPLEMENTO.setText("");
        
    }//GEN-LAST:event_NovojButton1ActionPerformed

    private void TxtPesquisaNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisaNomeKeyReleased
        // TODO add your handling code here:
       
        String nome = "%" +TxtPesquisaNome.getText() +"%";
        FuncionarioDao dao = new FuncionarioDao();
        List<FuncionarioBean> lista = dao.pesquisarNome(nome);
        DefaultTableModel dados =(DefaultTableModel)ListaDeFuncionariosjTable1.getModel();
        dados.setNumRows(0);
        
        for(FuncionarioBean c : lista){
            dados.addRow(new Object[]{
                c.getId(),
               c.getNome(),
               c.getRg(),
               c.getCpf(),
               c.getEmail(),
               c.getSenha(),
               c.getCargo(),
               c.getNivel_acesso(),
               c.getTelefone(),
               c.getCelular(),
              c.getCep(),
               c.getEndereco(),
               c.getNumero(),
              c.getComplemento(),
                c.getBairro(),
               c.getCidade(),
               c.getEstado()
            });
                  
       }
       
    }//GEN-LAST:event_TxtPesquisaNomeKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
          String nome = "%" +TxtPesquisaNome.getText() +"%";
        FuncionarioDao dao = new FuncionarioDao();
        List<FuncionarioBean> lista = dao.pesquisarNome(nome);
        DefaultTableModel dados =(DefaultTableModel)ListaDeFuncionariosjTable1.getModel();
        dados.setNumRows(0);
        
        for(FuncionarioBean c : lista){
            dados.addRow(new Object[]{
                c.getId(),
               c.getNome(),
               c.getRg(),
               c.getCpf(),
               c.getEmail(),
               c.getSenha(),
               c.getCargo(),
               c.getNivel_acesso(),
               c.getTelefone(),
               c.getCelular(),
              c.getCep(),
               c.getEndereco(),
               c.getNumero(),
              c.getComplemento(),
                c.getBairro(),
               c.getCidade(),
               c.getEstado()
            });
                  
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void TxtPesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPesquisaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPesquisaNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CONSULTACLIENTES;
    private javax.swing.JButton EditarjButton3;
    private javax.swing.JPanel GUIA_DADOS_PESSOAIS;
    private javax.swing.JTable ListaDeFuncionariosjTable1;
    private javax.swing.JComboBox<String> NivelAcessojComboBox1;
    private javax.swing.JButton NovojButton1;
    private javax.swing.JTabbedPane PainelDeGuiasjTabbedPane1;
    private javax.swing.JButton SalvarjButton2;
    private javax.swing.JTextField TxtBAIRRO;
    private javax.swing.JTextField TxtCARGO;
    private javax.swing.JTextField TxtCELULAR;
    private javax.swing.JTextField TxtCEP;
    private javax.swing.JTextField TxtCIDADE;
    private javax.swing.JTextField TxtCODIGO;
    private javax.swing.JTextArea TxtCOMPLEMENTO;
    private javax.swing.JTextField TxtCPF;
    private javax.swing.JTextField TxtEMAIL;
    private javax.swing.JTextField TxtENDERECO;
    private javax.swing.JTextField TxtNOME;
    private javax.swing.JTextField TxtNUMERO;
    private javax.swing.JTextField TxtPesquisaNome;
    private javax.swing.JTextField TxtRG;
    private javax.swing.JPasswordField TxtSENHA;
    private javax.swing.JTextField TxtTELEFONE;
    private javax.swing.JButton excluirjButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> ufjComboBox1;
    // End of variables declaration//GEN-END:variables
}
