/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bean.ClienteBean;
import Model.Bean.ProdutoBean;
import Model.Bean.UtilBean;
import Model.Dao.ClienteDao;
import Model.Bean.FornecedoresBean;
import Model.Dao.FornecedoresDao;
import Model.Dao.ProdutoDao;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author levi1
 */
public class EstoqueProdutoView extends javax.swing.JFrame {

    int idProduto, qtd_atualizado;
    
    public void Listar(){
        ProdutoDao dao = new ProdutoDao();
        List<ProdutoBean> lista = dao.ListarProdutos();
        DefaultTableModel produtos = (DefaultTableModel) ListaDeProdutosjTable1.getModel();
        produtos.setNumRows(0);
        for(ProdutoBean p:lista){
            produtos.addRow(new Object[]{
            
                p.getId(),
               p.getDescricao(),
               p.getPreco(),
               p.getQtd(),
               p.getFornecedor().getNome()
        });
        }
    }
    
    
    /**
     * Creates new form CadastroClientesView
     */
    public EstoqueProdutoView() {
        initComponents();
        TextEM_ESTOQUE.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/ImagensView/FundoLogin.jpg"));
        Image image = icon.getImage();
        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        PainelDeGuiasjTabbedPane1 = new javax.swing.JTabbedPane();
        CONSULTAPRODUTOS = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TxtPesquisaDescricao = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaDeProdutosjTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TextEM_ESTOQUE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextQTD_novo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("CONTROLE DE ESTOQUE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        PainelDeGuiasjTabbedPane1.setBackground(new java.awt.Color(204, 255, 255));

        CONSULTAPRODUTOS.setBackground(new java.awt.Color(204, 255, 255));

        jLabel10.setText("DESCRICAO");

        TxtPesquisaDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPesquisaDescricaoKeyReleased(evt);
            }
        });

        ListaDeProdutosjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRICAO", "PRECO", "QTD", "FORNECEDORES"
            }
        ));
        ListaDeProdutosjTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaDeProdutosjTable1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ListaDeProdutosjTable1MouseReleased(evt);
            }
        });
        ListaDeProdutosjTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ListaDeProdutosjTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(ListaDeProdutosjTable1);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/7479647_search_magnifier_zoom_magnifying_find_icon(1).png"))); // NOI18N
        jButton6.setText("PESQUISAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel5.setText("EM ESTOQUE :");

        jLabel7.setText("QUANTIDADE");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensView/299068_add_sign_icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CONSULTAPRODUTOSLayout = new javax.swing.GroupLayout(CONSULTAPRODUTOS);
        CONSULTAPRODUTOS.setLayout(CONSULTAPRODUTOSLayout);
        CONSULTAPRODUTOSLayout.setHorizontalGroup(
            CONSULTAPRODUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONSULTAPRODUTOSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtPesquisaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CONSULTAPRODUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
            .addGroup(CONSULTAPRODUTOSLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextEM_ESTOQUE, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextQTD_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CONSULTAPRODUTOSLayout.setVerticalGroup(
            CONSULTAPRODUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONSULTAPRODUTOSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CONSULTAPRODUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TxtPesquisaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CONSULTAPRODUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CONSULTAPRODUTOSLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CONSULTAPRODUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(CONSULTAPRODUTOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextEM_ESTOQUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(TextQTD_novo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(CONSULTAPRODUTOSLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PainelDeGuiasjTabbedPane1.addTab("ESTOQUE PRODUTOS", CONSULTAPRODUTOS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PainelDeGuiasjTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelDeGuiasjTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        Listar();
        
    }//GEN-LAST:event_formWindowActivated

    private void ListaDeProdutosjTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDeProdutosjTable1MouseReleased
        // TODO add your handling code here:        
        
        
    }//GEN-LAST:event_ListaDeProdutosjTable1MouseReleased

    private void ListaDeProdutosjTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDeProdutosjTable1MouseClicked
        // TODO add your handling code here:
        
              PainelDeGuiasjTabbedPane1.setSelectedIndex(0);
                idProduto= Integer.parseInt(ListaDeProdutosjTable1.getValueAt(ListaDeProdutosjTable1.getSelectedRow(), 0).toString());
            TxtPesquisaDescricao.setText(ListaDeProdutosjTable1.getValueAt(ListaDeProdutosjTable1.getSelectedRow(), 1).toString());
           TextEM_ESTOQUE.setText(ListaDeProdutosjTable1.getValueAt(ListaDeProdutosjTable1.getSelectedRow(), 3).toString());
            //TextQTD_novo.setText(ListaDeProdutosjTable1.getValueAt(ListaDeProdutosjTable1.getSelectedRow(), 4).toString());
           
    }//GEN-LAST:event_ListaDeProdutosjTable1MouseClicked

    private void ListaDeProdutosjTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ListaDeProdutosjTable1KeyReleased
        // TODO add your handling code here:
        
        
                                      
        
    }//GEN-LAST:event_ListaDeProdutosjTable1KeyReleased

    private void TxtPesquisaDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisaDescricaoKeyReleased
        // TODO add your handling code here:
       
        String nome = "%"+TxtPesquisaDescricao.getText()+ "%";
           ProdutoDao dao = new ProdutoDao();
           List<ProdutoBean> lista = dao.pesquisaNomeProduto(nome);
          DefaultTableModel dados =(DefaultTableModel)ListaDeProdutosjTable1.getModel();
       dados.setNumRows(0);
          for(ProdutoBean p: lista){
              dados.addRow(new Object[]{
              p.getId(),
                  p.getDescricao(),
                  p.getPreco(),
                  p.getQtd(),
                  p.getFornecedor().getNome()
          });
          }
    }//GEN-LAST:event_TxtPesquisaDescricaoKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         String nome = "%"+TxtPesquisaDescricao.getText()+ "%";
           ProdutoDao dao = new ProdutoDao();
           List<ProdutoBean> lista = dao.pesquisaNomeProduto(nome);
          DefaultTableModel dados =(DefaultTableModel)ListaDeProdutosjTable1.getModel();
       dados.setNumRows(0);
          for(ProdutoBean p: lista){
              dados.addRow(new Object[]{
              p.getId(),
                  p.getDescricao(),
                  p.getPreco(),
                  p.getQtd(),
                  p.getFornecedor().getNome()
          });
          }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            
                int qtd_emEstoque, qtd;
        qtd_emEstoque = Integer.valueOf(TextEM_ESTOQUE.getText());
        qtd = Integer.valueOf(TextQTD_novo.getText());
        qtd_atualizado = qtd_emEstoque + qtd;
        ProdutoDao dao = new ProdutoDao();
        dao.adicDeEstoque(idProduto, qtd_atualizado);
   
;       new UtilBean().LimpaCampos(CONSULTAPRODUTOS);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro "+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstoqueProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstoqueProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstoqueProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstoqueProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstoqueProdutoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CONSULTAPRODUTOS;
    private javax.swing.JTable ListaDeProdutosjTable1;
    private javax.swing.JTabbedPane PainelDeGuiasjTabbedPane1;
    private javax.swing.JTextField TextEM_ESTOQUE;
    private javax.swing.JTextField TextQTD_novo;
    private javax.swing.JTextField TxtPesquisaDescricao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
